/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BurgerButton: typeof import('./src/components/ui/BurgerButton.vue')['default']
    ButtonFX: typeof import('./src/components/ui/ButtonFX.vue')['default']
    GradientButton: typeof import('./src/components/ui/GradientButton.vue')['default']
    ImgNext: typeof import('./src/components/ui/ImgNext.vue')['default']
    ProgressBar: typeof import('./src/components/ui/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spinner: typeof import('./src/components/ui/Spinner.vue')['default']
    SVGCircle: typeof import('./src/components/ui/SVGCircle.vue')['default']
  }
}
